packages:
  - .
  - apps/*
  - packages/*

overrides:
  viem: 2.47.11

onlyBuiltDependencies:
  - "@reown/appkit"
  - "@tailwindcss/oxide"
  - bufferutil
  - esbuild
  - keccak
  - sharp
  - unrs-resolver
  - utf-8-validate

allowBuilds:
  '@reown/appkit': true
