/**
 * Curated theme presets for the playground configurator.
 *
 * Color values sourced from tweakcn (https://github.com/jnsahaj/tweakcn)
 * and stored as hex for easy visual inspection. The theme-utils module
 * converts to OKLCH at export time to match the widget's default.css format.
 *
 * Each preset defines light + dark color maps for the 26 shadcn CSS
 * variables used by @aomi-labs/widget-lib.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** The 26 color variable keys + radius used by the widget theme. */
export type ThemeColors = {
  background: string;
  foreground: string;
  card: string;
  "card-foreground": string;
  popover: string;
  "popover-foreground": string;
  primary: string;
  "primary-foreground": string;
  secondary: string;
  "secondary-foreground": string;
  muted: string;
  "muted-foreground": string;
  accent: string;
  "accent-foreground": string;
  destructive: string;
  "destructive-foreground": string;
  border: string;
  input: string;
  ring: string;
  "chart-1": string;
  "chart-2": string;
  "chart-3": string;
  "chart-4": string;
  "chart-5": string;
  sidebar: string;
  "sidebar-foreground": string;
  "sidebar-primary": string;
  "sidebar-primary-foreground": string;
  "sidebar-accent": string;
  "sidebar-accent-foreground": string;
  "sidebar-border": string;
  "sidebar-ring": string;
};

export type ThemePreset = {
  id: string;
  label: string;
  light: ThemeColors;
  dark: ThemeColors;
  radius: string;
  /** Hex preview colors for the swatch grid (no conversion needed). */
  preview: { primary: string; secondary: string; bg: string };
};

// ---------------------------------------------------------------------------
// Color variable keys (in order for CSS generation)
// ---------------------------------------------------------------------------

export const THEME_COLOR_KEYS: (keyof ThemeColors)[] = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "border",
  "input",
  "ring",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
  "sidebar",
  "sidebar-foreground",
  "sidebar-primary",
  "sidebar-primary-foreground",
  "sidebar-accent",
  "sidebar-accent-foreground",
  "sidebar-border",
  "sidebar-ring",
];

/** Subset of keys shown in the color-override UI. */
export const EDITABLE_COLOR_KEYS: { key: keyof ThemeColors; label: string }[] = [
  { key: "primary", label: "Primary" },
  { key: "background", label: "Background" },
  { key: "secondary", label: "Secondary" },
  { key: "accent", label: "Accent" },
  { key: "muted", label: "Muted" },
  { key: "border", label: "Border" },
  { key: "destructive", label: "Destructive" },
  { key: "foreground", label: "Foreground" },
];

// ---------------------------------------------------------------------------
// Presets
// ---------------------------------------------------------------------------

export const THEME_PRESETS: ThemePreset[] = [
  // ── Default (matches widget default.css) ──────────────────────────────
  {
    id: "default",
    label: "Default",
    radius: "0.625rem",
    preview: { primary: "#1a1a1a", secondary: "#f5f5f5", bg: "#ffffff" },
    light: {
      background: "#ffffff",
      foreground: "#1c1917",
      card: "#ffffff",
      "card-foreground": "#1c1917",
      popover: "#ffffff",
      "popover-foreground": "#1c1917",
      primary: "#1a1a1a",
      "primary-foreground": "#fafafa",
      secondary: "#f5f5f5",
      "secondary-foreground": "#1a1a1a",
      muted: "#f5f5f5",
      "muted-foreground": "#737373",
      accent: "#f5f5f5",
      "accent-foreground": "#1a1a1a",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#e5e5e5",
      input: "#e5e5e5",
      ring: "#a3a3a3",
      "chart-1": "#e76e50",
      "chart-2": "#2a9d90",
      "chart-3": "#274754",
      "chart-4": "#e8c468",
      "chart-5": "#f4a462",
      sidebar: "#fafafa",
      "sidebar-foreground": "#1c1917",
      "sidebar-primary": "#1a1a1a",
      "sidebar-primary-foreground": "#fafafa",
      "sidebar-accent": "#f5f5f5",
      "sidebar-accent-foreground": "#1a1a1a",
      "sidebar-border": "#e5e5e5",
      "sidebar-ring": "#a3a3a3",
    },
    dark: {
      background: "#1c1917",
      foreground: "#fafafa",
      card: "#1a1a1a",
      "card-foreground": "#fafafa",
      popover: "#1a1a1a",
      "popover-foreground": "#fafafa",
      primary: "#e5e5e5",
      "primary-foreground": "#1a1a1a",
      secondary: "#2a2a2a",
      "secondary-foreground": "#fafafa",
      muted: "#2a2a2a",
      "muted-foreground": "#a3a3a3",
      accent: "#2a2a2a",
      "accent-foreground": "#fafafa",
      destructive: "#ef4444",
      "destructive-foreground": "#fafafa",
      border: "#333333",
      input: "#404040",
      ring: "#737373",
      "chart-1": "#5b9bd5",
      "chart-2": "#70ad47",
      "chart-3": "#ffc000",
      "chart-4": "#c05fd0",
      "chart-5": "#ed7d31",
      sidebar: "#1a1a1a",
      "sidebar-foreground": "#fafafa",
      "sidebar-primary": "#5b9bd5",
      "sidebar-primary-foreground": "#fafafa",
      "sidebar-accent": "#2a2a2a",
      "sidebar-accent-foreground": "#fafafa",
      "sidebar-border": "#333333",
      "sidebar-ring": "#737373",
    },
  },

  // ── Modern Minimal ────────────────────────────────────────────────────
  {
    id: "modern-minimal",
    label: "Modern Minimal",
    radius: "0.375rem",
    preview: { primary: "#3b82f6", secondary: "#f3f4f6", bg: "#ffffff" },
    light: {
      background: "#ffffff",
      foreground: "#333333",
      card: "#ffffff",
      "card-foreground": "#333333",
      popover: "#ffffff",
      "popover-foreground": "#333333",
      primary: "#3b82f6",
      "primary-foreground": "#ffffff",
      secondary: "#f3f4f6",
      "secondary-foreground": "#4b5563",
      muted: "#f9fafb",
      "muted-foreground": "#6b7280",
      accent: "#e0f2fe",
      "accent-foreground": "#1e3a8a",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#e5e7eb",
      input: "#e5e7eb",
      ring: "#3b82f6",
      "chart-1": "#3b82f6",
      "chart-2": "#2563eb",
      "chart-3": "#1d4ed8",
      "chart-4": "#1e40af",
      "chart-5": "#1e3a8a",
      sidebar: "#f9fafb",
      "sidebar-foreground": "#333333",
      "sidebar-primary": "#3b82f6",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#e0f2fe",
      "sidebar-accent-foreground": "#1e3a8a",
      "sidebar-border": "#e5e7eb",
      "sidebar-ring": "#3b82f6",
    },
    dark: {
      background: "#171717",
      foreground: "#e5e5e5",
      card: "#262626",
      "card-foreground": "#e5e5e5",
      popover: "#262626",
      "popover-foreground": "#e5e5e5",
      primary: "#3b82f6",
      "primary-foreground": "#ffffff",
      secondary: "#262626",
      "secondary-foreground": "#e5e5e5",
      muted: "#1f1f1f",
      "muted-foreground": "#a3a3a3",
      accent: "#1e3a8a",
      "accent-foreground": "#bfdbfe",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#404040",
      input: "#404040",
      ring: "#3b82f6",
      "chart-1": "#60a5fa",
      "chart-2": "#3b82f6",
      "chart-3": "#2563eb",
      "chart-4": "#1d4ed8",
      "chart-5": "#1e40af",
      sidebar: "#171717",
      "sidebar-foreground": "#e5e5e5",
      "sidebar-primary": "#3b82f6",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#1e3a8a",
      "sidebar-accent-foreground": "#bfdbfe",
      "sidebar-border": "#404040",
      "sidebar-ring": "#3b82f6",
    },
  },

  // ── Violet Bloom ──────────────────────────────────────────────────────
  {
    id: "violet-bloom",
    label: "Violet Bloom",
    radius: "1.4rem",
    preview: { primary: "#7033ff", secondary: "#edf0f4", bg: "#fdfdfd" },
    light: {
      background: "#fdfdfd",
      foreground: "#000000",
      card: "#fdfdfd",
      "card-foreground": "#000000",
      popover: "#fcfcfc",
      "popover-foreground": "#000000",
      primary: "#7033ff",
      "primary-foreground": "#ffffff",
      secondary: "#edf0f4",
      "secondary-foreground": "#080808",
      muted: "#f5f5f5",
      "muted-foreground": "#525252",
      accent: "#e2ebff",
      "accent-foreground": "#1e69dc",
      destructive: "#e54b4f",
      "destructive-foreground": "#ffffff",
      border: "#e7e7ee",
      input: "#ebebeb",
      ring: "#000000",
      "chart-1": "#4ac885",
      "chart-2": "#7033ff",
      "chart-3": "#fd822b",
      "chart-4": "#3276e4",
      "chart-5": "#747474",
      sidebar: "#f5f8fb",
      "sidebar-foreground": "#000000",
      "sidebar-primary": "#000000",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#ebebeb",
      "sidebar-accent-foreground": "#000000",
      "sidebar-border": "#ebebeb",
      "sidebar-ring": "#000000",
    },
    dark: {
      background: "#1a1b1e",
      foreground: "#f0f0f0",
      card: "#222327",
      "card-foreground": "#f0f0f0",
      popover: "#222327",
      "popover-foreground": "#f0f0f0",
      primary: "#8c5cff",
      "primary-foreground": "#ffffff",
      secondary: "#2a2c33",
      "secondary-foreground": "#f0f0f0",
      muted: "#2a2c33",
      "muted-foreground": "#a0a0a0",
      accent: "#1e293b",
      "accent-foreground": "#79c0ff",
      destructive: "#f87171",
      "destructive-foreground": "#ffffff",
      border: "#33353a",
      input: "#33353a",
      ring: "#8c5cff",
      "chart-1": "#4ade80",
      "chart-2": "#8c5cff",
      "chart-3": "#fca5a5",
      "chart-4": "#5993f4",
      "chart-5": "#a0a0a0",
      sidebar: "#161618",
      "sidebar-foreground": "#f0f0f0",
      "sidebar-primary": "#8c5cff",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#2a2c33",
      "sidebar-accent-foreground": "#8c5cff",
      "sidebar-border": "#33353a",
      "sidebar-ring": "#8c5cff",
    },
  },

  // ── Ocean Breeze ──────────────────────────────────────────────────────
  {
    id: "ocean-breeze",
    label: "Ocean Breeze",
    radius: "0.5rem",
    preview: { primary: "#22c55e", secondary: "#e0f2fe", bg: "#f0f8ff" },
    light: {
      background: "#f0f8ff",
      foreground: "#374151",
      card: "#ffffff",
      "card-foreground": "#374151",
      popover: "#ffffff",
      "popover-foreground": "#374151",
      primary: "#22c55e",
      "primary-foreground": "#ffffff",
      secondary: "#e0f2fe",
      "secondary-foreground": "#4b5563",
      muted: "#f3f4f6",
      "muted-foreground": "#6b7280",
      accent: "#d1fae5",
      "accent-foreground": "#374151",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#e5e7eb",
      input: "#e5e7eb",
      ring: "#22c55e",
      "chart-1": "#22c55e",
      "chart-2": "#10b981",
      "chart-3": "#059669",
      "chart-4": "#047857",
      "chart-5": "#065f46",
      sidebar: "#e0f2fe",
      "sidebar-foreground": "#374151",
      "sidebar-primary": "#22c55e",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#d1fae5",
      "sidebar-accent-foreground": "#374151",
      "sidebar-border": "#e5e7eb",
      "sidebar-ring": "#22c55e",
    },
    dark: {
      background: "#0f172a",
      foreground: "#d1d5db",
      card: "#1e293b",
      "card-foreground": "#d1d5db",
      popover: "#1e293b",
      "popover-foreground": "#d1d5db",
      primary: "#34d399",
      "primary-foreground": "#0f172a",
      secondary: "#2d3748",
      "secondary-foreground": "#a1a1aa",
      muted: "#19212e",
      "muted-foreground": "#6b7280",
      accent: "#374151",
      "accent-foreground": "#a1a1aa",
      destructive: "#ef4444",
      "destructive-foreground": "#0f172a",
      border: "#4b5563",
      input: "#4b5563",
      ring: "#34d399",
      "chart-1": "#34d399",
      "chart-2": "#2dd4bf",
      "chart-3": "#22c55e",
      "chart-4": "#10b981",
      "chart-5": "#059669",
      sidebar: "#1e293b",
      "sidebar-foreground": "#d1d5db",
      "sidebar-primary": "#34d399",
      "sidebar-primary-foreground": "#0f172a",
      "sidebar-accent": "#374151",
      "sidebar-accent-foreground": "#a1a1aa",
      "sidebar-border": "#4b5563",
      "sidebar-ring": "#34d399",
    },
  },

  // ── Claude ─────────────────────────────────────────────────────────────
  {
    id: "claude",
    label: "Claude",
    radius: "0.5rem",
    preview: { primary: "#c96442", secondary: "#e9e6dc", bg: "#faf9f5" },
    light: {
      background: "#faf9f5",
      foreground: "#3d3929",
      card: "#faf9f5",
      "card-foreground": "#141413",
      popover: "#ffffff",
      "popover-foreground": "#28261b",
      primary: "#c96442",
      "primary-foreground": "#ffffff",
      secondary: "#e9e6dc",
      "secondary-foreground": "#535146",
      muted: "#ede9de",
      "muted-foreground": "#83827d",
      accent: "#e9e6dc",
      "accent-foreground": "#28261b",
      destructive: "#141413",
      "destructive-foreground": "#ffffff",
      border: "#dad9d4",
      input: "#b4b2a7",
      ring: "#c96442",
      "chart-1": "#b05730",
      "chart-2": "#9c87f5",
      "chart-3": "#ded8c4",
      "chart-4": "#dbd3f0",
      "chart-5": "#b4552d",
      sidebar: "#f5f4ee",
      "sidebar-foreground": "#3d3d3a",
      "sidebar-primary": "#c96442",
      "sidebar-primary-foreground": "#fbfbfb",
      "sidebar-accent": "#e9e6dc",
      "sidebar-accent-foreground": "#343434",
      "sidebar-border": "#ebebeb",
      "sidebar-ring": "#b5b5b5",
    },
    dark: {
      background: "#262624",
      foreground: "#c3c0b6",
      card: "#262624",
      "card-foreground": "#faf9f5",
      popover: "#30302e",
      "popover-foreground": "#e5e5e2",
      primary: "#d97757",
      "primary-foreground": "#ffffff",
      secondary: "#faf9f5",
      "secondary-foreground": "#30302e",
      muted: "#1b1b19",
      "muted-foreground": "#b7b5a9",
      accent: "#1a1915",
      "accent-foreground": "#f5f4ee",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#3e3e38",
      input: "#52514a",
      ring: "#d97757",
      "chart-1": "#b05730",
      "chart-2": "#9c87f5",
      "chart-3": "#1a1915",
      "chart-4": "#2f2b48",
      "chart-5": "#b4552d",
      sidebar: "#1f1e1d",
      "sidebar-foreground": "#c3c0b6",
      "sidebar-primary": "#343434",
      "sidebar-primary-foreground": "#fbfbfb",
      "sidebar-accent": "#0f0f0e",
      "sidebar-accent-foreground": "#c3c0b6",
      "sidebar-border": "#ebebeb",
      "sidebar-ring": "#b5b5b5",
    },
  },

  // ── Cyberpunk ─────────────────────────────────────────────────────────
  {
    id: "cyberpunk",
    label: "Cyberpunk",
    radius: "0.5rem",
    preview: { primary: "#ff00c8", secondary: "#f0f0ff", bg: "#f8f9fa" },
    light: {
      background: "#f8f9fa",
      foreground: "#0c0c1d",
      card: "#ffffff",
      "card-foreground": "#0c0c1d",
      popover: "#ffffff",
      "popover-foreground": "#0c0c1d",
      primary: "#ff00c8",
      "primary-foreground": "#ffffff",
      secondary: "#f0f0ff",
      "secondary-foreground": "#0c0c1d",
      muted: "#f0f0ff",
      "muted-foreground": "#0c0c1d",
      accent: "#00ffcc",
      "accent-foreground": "#0c0c1d",
      destructive: "#ff3d00",
      "destructive-foreground": "#ffffff",
      border: "#dfe6e9",
      input: "#dfe6e9",
      ring: "#ff00c8",
      "chart-1": "#ff00c8",
      "chart-2": "#9000ff",
      "chart-3": "#00e5ff",
      "chart-4": "#00ffcc",
      "chart-5": "#ffe600",
      sidebar: "#f0f0ff",
      "sidebar-foreground": "#0c0c1d",
      "sidebar-primary": "#ff00c8",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#00ffcc",
      "sidebar-accent-foreground": "#0c0c1d",
      "sidebar-border": "#dfe6e9",
      "sidebar-ring": "#ff00c8",
    },
    dark: {
      background: "#0c0c1d",
      foreground: "#eceff4",
      card: "#1e1e3f",
      "card-foreground": "#eceff4",
      popover: "#1e1e3f",
      "popover-foreground": "#eceff4",
      primary: "#ff00c8",
      "primary-foreground": "#ffffff",
      secondary: "#1e1e3f",
      "secondary-foreground": "#eceff4",
      muted: "#151530",
      "muted-foreground": "#8085a6",
      accent: "#00ffcc",
      "accent-foreground": "#0c0c1d",
      destructive: "#ff3d00",
      "destructive-foreground": "#ffffff",
      border: "#2e2e5e",
      input: "#2e2e5e",
      ring: "#ff00c8",
      "chart-1": "#ff00c8",
      "chart-2": "#9000ff",
      "chart-3": "#00e5ff",
      "chart-4": "#00ffcc",
      "chart-5": "#ffe600",
      sidebar: "#0c0c1d",
      "sidebar-foreground": "#eceff4",
      "sidebar-primary": "#ff00c8",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#00ffcc",
      "sidebar-accent-foreground": "#0c0c1d",
      "sidebar-border": "#2e2e5e",
      "sidebar-ring": "#ff00c8",
    },
  },

  // ── Midnight Bloom ────────────────────────────────────────────────────
  {
    id: "midnight-bloom",
    label: "Midnight Bloom",
    radius: "0.5rem",
    preview: { primary: "#6c5ce7", secondary: "#a1c9f2", bg: "#f9f9f9" },
    light: {
      background: "#f9f9f9",
      foreground: "#333333",
      card: "#ffffff",
      "card-foreground": "#333333",
      popover: "#ffffff",
      "popover-foreground": "#333333",
      primary: "#6c5ce7",
      "primary-foreground": "#ffffff",
      secondary: "#a1c9f2",
      "secondary-foreground": "#333333",
      muted: "#c9c4b5",
      "muted-foreground": "#6e6e6e",
      accent: "#8b9467",
      "accent-foreground": "#ffffff",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#d4d4d4",
      input: "#d4d4d4",
      ring: "#6c5ce7",
      "chart-1": "#6c5ce7",
      "chart-2": "#8e44ad",
      "chart-3": "#4b0082",
      "chart-4": "#6495ed",
      "chart-5": "#4682b4",
      sidebar: "#f9f9f9",
      "sidebar-foreground": "#333333",
      "sidebar-primary": "#6c5ce7",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#8b9467",
      "sidebar-accent-foreground": "#ffffff",
      "sidebar-border": "#d4d4d4",
      "sidebar-ring": "#6c5ce7",
    },
    dark: {
      background: "#1a1d23",
      foreground: "#e5e5e5",
      card: "#2f3436",
      "card-foreground": "#e5e5e5",
      popover: "#2f3436",
      "popover-foreground": "#e5e5e5",
      primary: "#6c5ce7",
      "primary-foreground": "#ffffff",
      secondary: "#4b0082",
      "secondary-foreground": "#e5e5e5",
      muted: "#444444",
      "muted-foreground": "#a3a3a3",
      accent: "#6495ed",
      "accent-foreground": "#e5e5e5",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#444444",
      input: "#444444",
      ring: "#6c5ce7",
      "chart-1": "#6c5ce7",
      "chart-2": "#8e44ad",
      "chart-3": "#4b0082",
      "chart-4": "#6495ed",
      "chart-5": "#4682b4",
      sidebar: "#1a1d23",
      "sidebar-foreground": "#e5e5e5",
      "sidebar-primary": "#6c5ce7",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#6495ed",
      "sidebar-accent-foreground": "#e5e5e5",
      "sidebar-border": "#444444",
      "sidebar-ring": "#6c5ce7",
    },
  },

  // ── Catppuccin ────────────────────────────────────────────────────────
  {
    id: "catppuccin",
    label: "Catppuccin",
    radius: "0.35rem",
    preview: { primary: "#8839ef", secondary: "#ccd0da", bg: "#eff1f5" },
    light: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      card: "#ffffff",
      "card-foreground": "#4c4f69",
      popover: "#ccd0da",
      "popover-foreground": "#4c4f69",
      primary: "#8839ef",
      "primary-foreground": "#ffffff",
      secondary: "#ccd0da",
      "secondary-foreground": "#4c4f69",
      muted: "#dce0e8",
      "muted-foreground": "#6c6f85",
      accent: "#04a5e5",
      "accent-foreground": "#ffffff",
      destructive: "#d20f39",
      "destructive-foreground": "#ffffff",
      border: "#bcc0cc",
      input: "#ccd0da",
      ring: "#8839ef",
      "chart-1": "#8839ef",
      "chart-2": "#04a5e5",
      "chart-3": "#40a02b",
      "chart-4": "#fe640b",
      "chart-5": "#dc8a78",
      sidebar: "#e6e9ef",
      "sidebar-foreground": "#4c4f69",
      "sidebar-primary": "#8839ef",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#04a5e5",
      "sidebar-accent-foreground": "#ffffff",
      "sidebar-border": "#bcc0cc",
      "sidebar-ring": "#8839ef",
    },
    dark: {
      background: "#181825",
      foreground: "#cdd6f4",
      card: "#1e1e2e",
      "card-foreground": "#cdd6f4",
      popover: "#45475a",
      "popover-foreground": "#cdd6f4",
      primary: "#cba6f7",
      "primary-foreground": "#1e1e2e",
      secondary: "#585b70",
      "secondary-foreground": "#cdd6f4",
      muted: "#292c3c",
      "muted-foreground": "#a6adc8",
      accent: "#89dceb",
      "accent-foreground": "#1e1e2e",
      destructive: "#f38ba8",
      "destructive-foreground": "#1e1e2e",
      border: "#313244",
      input: "#313244",
      ring: "#cba6f7",
      "chart-1": "#cba6f7",
      "chart-2": "#89dceb",
      "chart-3": "#a6e3a1",
      "chart-4": "#fab387",
      "chart-5": "#f5e0dc",
      sidebar: "#11111b",
      "sidebar-foreground": "#cdd6f4",
      "sidebar-primary": "#cba6f7",
      "sidebar-primary-foreground": "#1e1e2e",
      "sidebar-accent": "#89dceb",
      "sidebar-accent-foreground": "#1e1e2e",
      "sidebar-border": "#45475a",
      "sidebar-ring": "#cba6f7",
    },
  },

  // ── Nature ────────────────────────────────────────────────────────────
  {
    id: "nature",
    label: "Nature",
    radius: "0.5rem",
    preview: { primary: "#2e7d32", secondary: "#e8f5e9", bg: "#f8f5f0" },
    light: {
      background: "#f8f5f0",
      foreground: "#3e2723",
      card: "#f8f5f0",
      "card-foreground": "#3e2723",
      popover: "#f8f5f0",
      "popover-foreground": "#3e2723",
      primary: "#2e7d32",
      "primary-foreground": "#ffffff",
      secondary: "#e8f5e9",
      "secondary-foreground": "#1b5e20",
      muted: "#f0e9e0",
      "muted-foreground": "#6d4c41",
      accent: "#c8e6c9",
      "accent-foreground": "#1b5e20",
      destructive: "#c62828",
      "destructive-foreground": "#ffffff",
      border: "#e0d6c9",
      input: "#e0d6c9",
      ring: "#2e7d32",
      "chart-1": "#4caf50",
      "chart-2": "#388e3c",
      "chart-3": "#2e7d32",
      "chart-4": "#1b5e20",
      "chart-5": "#0a1f0c",
      sidebar: "#f0e9e0",
      "sidebar-foreground": "#3e2723",
      "sidebar-primary": "#2e7d32",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#c8e6c9",
      "sidebar-accent-foreground": "#1b5e20",
      "sidebar-border": "#e0d6c9",
      "sidebar-ring": "#2e7d32",
    },
    dark: {
      background: "#1c2a1f",
      foreground: "#f0ebe5",
      card: "#2d3a2e",
      "card-foreground": "#f0ebe5",
      popover: "#2d3a2e",
      "popover-foreground": "#f0ebe5",
      primary: "#4caf50",
      "primary-foreground": "#0a1f0c",
      secondary: "#3e4a3d",
      "secondary-foreground": "#d7e0d6",
      muted: "#252f26",
      "muted-foreground": "#d7cfc4",
      accent: "#388e3c",
      "accent-foreground": "#f0ebe5",
      destructive: "#c62828",
      "destructive-foreground": "#f0ebe5",
      border: "#3e4a3d",
      input: "#3e4a3d",
      ring: "#4caf50",
      "chart-1": "#81c784",
      "chart-2": "#66bb6a",
      "chart-3": "#4caf50",
      "chart-4": "#43a047",
      "chart-5": "#388e3c",
      sidebar: "#1c2a1f",
      "sidebar-foreground": "#f0ebe5",
      "sidebar-primary": "#4caf50",
      "sidebar-primary-foreground": "#0a1f0c",
      "sidebar-accent": "#388e3c",
      "sidebar-accent-foreground": "#f0ebe5",
      "sidebar-border": "#3e4a3d",
      "sidebar-ring": "#4caf50",
    },
  },

  // ── Amber Minimal ─────────────────────────────────────────────────────
  {
    id: "amber-minimal",
    label: "Amber Minimal",
    radius: "0.375rem",
    preview: { primary: "#f59e0b", secondary: "#f3f4f6", bg: "#ffffff" },
    light: {
      background: "#ffffff",
      foreground: "#262626",
      card: "#ffffff",
      "card-foreground": "#262626",
      popover: "#ffffff",
      "popover-foreground": "#262626",
      primary: "#f59e0b",
      "primary-foreground": "#000000",
      secondary: "#f3f4f6",
      "secondary-foreground": "#4b5563",
      muted: "#f9fafb",
      "muted-foreground": "#6b7280",
      accent: "#fffbeb",
      "accent-foreground": "#92400e",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#e5e7eb",
      input: "#e5e7eb",
      ring: "#f59e0b",
      "chart-1": "#f59e0b",
      "chart-2": "#d97706",
      "chart-3": "#b45309",
      "chart-4": "#92400e",
      "chart-5": "#78350f",
      sidebar: "#f9fafb",
      "sidebar-foreground": "#262626",
      "sidebar-primary": "#f59e0b",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#fffbeb",
      "sidebar-accent-foreground": "#92400e",
      "sidebar-border": "#e5e7eb",
      "sidebar-ring": "#f59e0b",
    },
    dark: {
      background: "#171717",
      foreground: "#e5e5e5",
      card: "#262626",
      "card-foreground": "#e5e5e5",
      popover: "#262626",
      "popover-foreground": "#e5e5e5",
      primary: "#f59e0b",
      "primary-foreground": "#000000",
      secondary: "#262626",
      "secondary-foreground": "#e5e5e5",
      muted: "#1f1f1f",
      "muted-foreground": "#a3a3a3",
      accent: "#92400e",
      "accent-foreground": "#fde68a",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#404040",
      input: "#404040",
      ring: "#f59e0b",
      "chart-1": "#fbbf24",
      "chart-2": "#d97706",
      "chart-3": "#92400e",
      "chart-4": "#b45309",
      "chart-5": "#92400e",
      sidebar: "#0f0f0f",
      "sidebar-foreground": "#e5e5e5",
      "sidebar-primary": "#f59e0b",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#92400e",
      "sidebar-accent-foreground": "#fde68a",
      "sidebar-border": "#404040",
      "sidebar-ring": "#f59e0b",
    },
  },

  // ── Supabase ──────────────────────────────────────────────────────────
  {
    id: "supabase",
    label: "Supabase",
    radius: "0.5rem",
    preview: { primary: "#72e3ad", secondary: "#ededed", bg: "#fcfcfc" },
    light: {
      background: "#fcfcfc",
      foreground: "#171717",
      card: "#fcfcfc",
      "card-foreground": "#171717",
      popover: "#fcfcfc",
      "popover-foreground": "#525252",
      primary: "#72e3ad",
      "primary-foreground": "#1e2723",
      secondary: "#fdfdfd",
      "secondary-foreground": "#171717",
      muted: "#ededed",
      "muted-foreground": "#202020",
      accent: "#ededed",
      "accent-foreground": "#202020",
      destructive: "#ca3214",
      "destructive-foreground": "#fffcfc",
      border: "#dfdfdf",
      input: "#f6f6f6",
      ring: "#72e3ad",
      "chart-1": "#72e3ad",
      "chart-2": "#3b82f6",
      "chart-3": "#8b5cf6",
      "chart-4": "#f59e0b",
      "chart-5": "#10b981",
      sidebar: "#fcfcfc",
      "sidebar-foreground": "#707070",
      "sidebar-primary": "#72e3ad",
      "sidebar-primary-foreground": "#1e2723",
      "sidebar-accent": "#ededed",
      "sidebar-accent-foreground": "#202020",
      "sidebar-border": "#dfdfdf",
      "sidebar-ring": "#72e3ad",
    },
    dark: {
      background: "#121212",
      foreground: "#e2e8f0",
      card: "#171717",
      "card-foreground": "#e2e8f0",
      popover: "#242424",
      "popover-foreground": "#a9a9a9",
      primary: "#006239",
      "primary-foreground": "#dde8e3",
      secondary: "#242424",
      "secondary-foreground": "#fafafa",
      muted: "#1f1f1f",
      "muted-foreground": "#a2a2a2",
      accent: "#313131",
      "accent-foreground": "#fafafa",
      destructive: "#541c15",
      "destructive-foreground": "#ede9e8",
      border: "#292929",
      input: "#242424",
      ring: "#4ade80",
      "chart-1": "#4ade80",
      "chart-2": "#60a5fa",
      "chart-3": "#a78bfa",
      "chart-4": "#fbbf24",
      "chart-5": "#2dd4bf",
      sidebar: "#121212",
      "sidebar-foreground": "#898989",
      "sidebar-primary": "#006239",
      "sidebar-primary-foreground": "#dde8e3",
      "sidebar-accent": "#313131",
      "sidebar-accent-foreground": "#fafafa",
      "sidebar-border": "#292929",
      "sidebar-ring": "#4ade80",
    },
  },

  // ── Mono ───────────────────────────────────────────────────────────────
  {
    id: "mono",
    label: "Mono",
    radius: "0rem",
    preview: { primary: "#737373", secondary: "#f5f5f5", bg: "#ffffff" },
    light: {
      background: "#ffffff",
      foreground: "#0a0a0a",
      card: "#ffffff",
      "card-foreground": "#0a0a0a",
      popover: "#ffffff",
      "popover-foreground": "#0a0a0a",
      primary: "#737373",
      "primary-foreground": "#fafafa",
      secondary: "#f5f5f5",
      "secondary-foreground": "#171717",
      muted: "#f5f5f5",
      "muted-foreground": "#717171",
      accent: "#f5f5f5",
      "accent-foreground": "#171717",
      destructive: "#e7000b",
      "destructive-foreground": "#f5f5f5",
      border: "#e5e5e5",
      input: "#e5e5e5",
      ring: "#a1a1a1",
      "chart-1": "#737373",
      "chart-2": "#737373",
      "chart-3": "#737373",
      "chart-4": "#737373",
      "chart-5": "#737373",
      sidebar: "#fafafa",
      "sidebar-foreground": "#0a0a0a",
      "sidebar-primary": "#171717",
      "sidebar-primary-foreground": "#fafafa",
      "sidebar-accent": "#f5f5f5",
      "sidebar-accent-foreground": "#171717",
      "sidebar-border": "#e5e5e5",
      "sidebar-ring": "#a1a1a1",
    },
    dark: {
      background: "#0a0a0a",
      foreground: "#fafafa",
      card: "#191919",
      "card-foreground": "#fafafa",
      popover: "#262626",
      "popover-foreground": "#fafafa",
      primary: "#737373",
      "primary-foreground": "#fafafa",
      secondary: "#262626",
      "secondary-foreground": "#fafafa",
      muted: "#262626",
      "muted-foreground": "#a1a1a1",
      accent: "#404040",
      "accent-foreground": "#fafafa",
      destructive: "#ff6467",
      "destructive-foreground": "#262626",
      border: "#383838",
      input: "#525252",
      ring: "#737373",
      "chart-1": "#737373",
      "chart-2": "#737373",
      "chart-3": "#737373",
      "chart-4": "#737373",
      "chart-5": "#737373",
      sidebar: "#171717",
      "sidebar-foreground": "#fafafa",
      "sidebar-primary": "#fafafa",
      "sidebar-primary-foreground": "#171717",
      "sidebar-accent": "#262626",
      "sidebar-accent-foreground": "#fafafa",
      "sidebar-border": "#ffffff",
      "sidebar-ring": "#525252",
    },
  },
];
