import { createHash } from "node:crypto";

import { DeployError, PathScopeError } from "./errors";
import { releaseTag } from "./release-tag";
import type {
  DeploymentManifest,
  PlatformDescriptor,
  StagedFile,
} from "./contract";
import type { SourceBundle } from "./types";

// =============================================================================
// deployment.json generation + the per-slug path guard
// =============================================================================

/** The manifest path the client owns; callers may not stage it themselves. */
export const RESERVED_MANIFEST_PATH = ".aomi/deployment.json";

export const DEPLOYMENT_DIR = ".aomi";
export const DEPLOYMENT_FILE = "deployment.json";

/** Mirror of publish_app.py `normalize_github_repo`. */
export function normalizeGithubRepo(repo: string): string {
  let r = repo.trim();
  for (const prefix of [
    "git@github.com:",
    "ssh://git@github.com/",
    "https://github.com/",
    "http://github.com/",
    "github.com/",
  ]) {
    if (r.startsWith(prefix)) {
      r = r.slice(prefix.length);
      break;
    }
  }
  if (r.endsWith(".git")) r = r.slice(0, -4);
  return r.replace(/^\/+|\/+$/g, "").toLowerCase();
}

export function toBytes(content: string | Uint8Array): Uint8Array {
  return typeof content === "string" ? Buffer.from(content, "utf8") : content;
}

export function sha256Prefixed(content: string | Uint8Array): string {
  return `sha256:${createHash("sha256").update(toBytes(content)).digest("hex")}`;
}

/** Normalize to posix and strip a redundant leading `./`. */
function toPosix(path: string): string {
  return path.replace(/\\/g, "/").replace(/^\.\//, "");
}

/**
 * The per-slug security guard. Validates every bundle path stays inside
 * `apps/<slug>/`, computes `{path, sha256, bytes}`, and returns the list sorted
 * by path (matching `aomi-git`'s ordering). Rejects:
 *   - absolute paths / `..` traversal
 *   - empty bundles
 *   - the reserved `.aomi/deployment.json` (the client generates it)
 *   - duplicate paths
 */
export function stageFiles(slug: string, bundle: SourceBundle): StagedFile[] {
  const entries = Object.entries(bundle);
  if (entries.length === 0) {
    throw new DeployError("EMPTY_BUNDLE", `no files to deploy for app \`${slug}\``);
  }

  const seen = new Set<string>();
  const staged: StagedFile[] = [];

  for (const [rawPath, content] of entries) {
    const path = toPosix(rawPath);

    if (path === "" || path === ".") {
      throw new PathScopeError(rawPath, `empty staged file path`);
    }
    if (path.startsWith("/")) {
      throw new PathScopeError(rawPath, `staged file path must be relative, got ${JSON.stringify(rawPath)}`);
    }
    if (path.split("/").includes("..")) {
      throw new PathScopeError(rawPath, `staged file path may not contain '..': ${JSON.stringify(rawPath)}`);
    }
    if (path === RESERVED_MANIFEST_PATH) {
      throw new PathScopeError(
        rawPath,
        `'${RESERVED_MANIFEST_PATH}' is generated by the deploy client and may not be supplied`,
      );
    }
    if (seen.has(path)) {
      throw new PathScopeError(rawPath, `duplicate staged file path: ${path}`);
    }
    seen.add(path);

    const bytes = toBytes(content);
    staged.push({
      path,
      sha256: sha256Prefixed(bytes),
      bytes: bytes.length,
    });
  }

  staged.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return staged;
}

export interface BuildManifestArgs {
  slug: string;
  displayName?: string;
  descriptor: PlatformDescriptor;
  staged: StagedFile[];
  sourceCommit: string;
  serverTags: string[];
  isPublic: boolean;
  /** Unix seconds; injectable for deterministic tests. */
  now?: number;
}

/** Build a contract-valid `.aomi/deployment.json` object. */
export function buildDeploymentManifest(args: BuildManifestArgs): DeploymentManifest {
  const { slug, descriptor, staged, sourceCommit, serverTags, isPublic } = args;
  const appPath = `${descriptor.app_path_prefix.replace(/^\/+|\/+$/g, "")}/${slug}`;
  const gitUrl = `https://github.com/${descriptor.source_repo}`;
  const now = args.now ?? Math.floor(Date.now() / 1000);

  return {
    app: {
      name: slug,
      display_name: args.displayName ?? slug,
      platform: descriptor.name,
      git: gitUrl,
      public: isPublic,
      server_tags: serverTags,
    },
    source: {
      commit: sourceCommit,
    },
    platform: {
      name: descriptor.name,
      github_repo: descriptor.source_repo,
      resolved_deploy_branch: descriptor.publish_branch,
    },
    target: {
      branch: descriptor.publish_branch,
      app_path: appPath,
      release_tag: releaseTag(slug, sourceCommit, descriptor.release_tag_convention),
      server_tags: serverTags,
    },
    state: {
      pushed: true,
      deployed: true,
      activated: false,
    },
    files: staged,
    updated_at: now,
  };
}

/**
 * Replicate the publish CI's `validate_deployment_manifest` checks. Used by the
 * contract-drift test and as optional defense before committing.
 */
export function validateManifest(
  manifest: DeploymentManifest,
  descriptor: PlatformDescriptor,
): void {
  const fail = (m: string): never => {
    throw new DeployError("GITHUB_COMMIT", `deployment manifest invalid: ${m}`);
  };

  if (manifest.platform?.name !== descriptor.name) {
    fail(`platform.name must be ${descriptor.name}`);
  }
  if (
    normalizeGithubRepo(manifest.platform.github_repo) !==
    normalizeGithubRepo(descriptor.source_repo)
  ) {
    fail(`platform.github_repo must resolve to ${descriptor.source_repo}`);
  }

  const slug = manifest.app?.name;
  if (!slug) fail("app.name must be a non-empty string");
  if (!/^[0-9a-f]{12,40}$/.test(manifest.source?.commit ?? "")) {
    fail("source.commit must be 12–40 lowercase hex");
  }
  if (!Array.isArray(manifest.files) || manifest.files.length === 0) {
    fail("files must be a non-empty array");
  }

  const expectedAppPath = `${descriptor.app_path_prefix.replace(/^\/+|\/+$/g, "")}/${slug}`;
  if (manifest.target?.app_path !== expectedAppPath) {
    fail(`target.app_path must be ${expectedAppPath}`);
  }
  const expectedTag = releaseTag(slug, manifest.source.commit, descriptor.release_tag_convention);
  if (manifest.target.release_tag !== expectedTag) {
    fail(`target.release_tag must be ${expectedTag}, got ${manifest.target.release_tag}`);
  }
}
