import { createHash } from "node:crypto";

import { DeployError, PathScopeError } from "./errors";
import type { StagedFile } from "./contract";
import type { SourceBundle } from "./types";

// =============================================================================
// deployment.json generation + the per-slug path guard
// =============================================================================

/** The manifest path the client owns; callers may not stage it themselves. */
export const RESERVED_MANIFEST_PATH = ".aomi/deployment.json";

export const DEPLOYMENT_DIR = ".aomi";
export const DEPLOYMENT_FILE = "deployment.json";

/** Mirror of publish_app.py `normalize_github_repo`. */
export function normalizeGithubRepo(repo: string): string {
  let r = repo.trim();
  for (const prefix of [
    "git@github.com:",
    "ssh://git@github.com/",
    "https://github.com/",
    "http://github.com/",
    "github.com/",
  ]) {
    if (r.startsWith(prefix)) {
      r = r.slice(prefix.length);
      break;
    }
  }
  if (r.endsWith(".git")) r = r.slice(0, -4);
  return r.replace(/^\/+|\/+$/g, "").toLowerCase();
}

export function toBytes(content: string | Uint8Array): Uint8Array {
  return typeof content === "string" ? Buffer.from(content, "utf8") : content;
}

export function sha256Prefixed(content: string | Uint8Array): string {
  return `sha256:${createHash("sha256").update(toBytes(content)).digest("hex")}`;
}

/** Normalize to posix and strip a redundant leading `./`. */
function toPosix(path: string): string {
  return path.replace(/\\/g, "/").replace(/^\.\//, "");
}

/**
 * The per-slug security guard. Validates every bundle path stays inside
 * `apps/<slug>/`, computes `{path, sha256, bytes}`, and returns the list sorted
 * by path (matching `aomi-git`'s ordering). Rejects:
 *   - absolute paths / `..` traversal
 *   - empty bundles
 *   - the reserved `.aomi/deployment.json` (the client generates it)
 *   - duplicate paths
 */
export function stageFiles(slug: string, bundle: SourceBundle): StagedFile[] {
  const entries = Object.entries(bundle);
  if (entries.length === 0) {
    throw new DeployError("EMPTY_BUNDLE", `no files to deploy for app \`${slug}\``);
  }

  const seen = new Set<string>();
  const staged: StagedFile[] = [];

  for (const [rawPath, content] of entries) {
    const path = toPosix(rawPath);

    if (path === "" || path === ".") {
      throw new PathScopeError(rawPath, `empty staged file path`);
    }
    if (path.startsWith("/")) {
      throw new PathScopeError(rawPath, `staged file path must be relative, got ${JSON.stringify(rawPath)}`);
    }
    if (path.split("/").includes("..")) {
      throw new PathScopeError(rawPath, `staged file path may not contain '..': ${JSON.stringify(rawPath)}`);
    }
    if (path === RESERVED_MANIFEST_PATH) {
      throw new PathScopeError(
        rawPath,
        `'${RESERVED_MANIFEST_PATH}' is generated by the deploy client and may not be supplied`,
      );
    }
    if (seen.has(path)) {
      throw new PathScopeError(rawPath, `duplicate staged file path: ${path}`);
    }
    seen.add(path);

    const bytes = toBytes(content);
    staged.push({
      path,
      sha256: sha256Prefixed(bytes),
      bytes: bytes.length,
    });
  }

  staged.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return staged;
}

// Manifest generation moved server-side (the backend builds + commits
// `.aomi/deployment.json` from the bundle it receives — Phase 6). The client no
// longer constructs or validates the manifest; it only stages + hashes files to
// derive a provenance commit and to fail-fast on out-of-scope paths.
