// @aomi-labs/deploy — server-side typed relay for the Aomi platform deploy API.
// (Service-identity/topology lives in @aomi-labs/service.)

export { BackendClient, assertServerOnly } from "./backend";

export {
  buildActivationRequest,
  buildActivationRequestDiscordBody,
  ACTIVATION_REQUEST_KIND,
  ACTIVATION_REQUEST_SOURCE,
  ACTIVATION_REQUEST_EMBED_COLOR,
} from "./activation-request";

export { missingRequiredSecrets } from "./secrets";

export {
  DeployError,
  BrowserEnvironmentError,
  BackendError,
  ActivationError,
} from "./errors";
export type { DeployErrorCode } from "./errors";

export type {
  AomiConfig,
  AuditEvent,
  BackendClientOptions,
  ServerTagsResult,
  SdkVersionStatus,
  SourceRef,
  DeployInput,
  PreflightInput,
  DeployStatus,
  CiStatus,
  DeployResult,
  DeployPayload,
  Source,
  Platform,
  AppRecord,
  AppFileRecord,
  ReleaseTags,
  ActivateInput,
  ActivateResult,
  ActivationPromotion,
  ActivatedApp,
  StatusInput,
  DeploymentStatus,
  DeploymentAppStatus,
  ProgressModel,
  DeploymentEventKind,
  DeploymentProgressEvent,
  WatchDeploymentOptions,
  TokenScope,
  MintTokenInput,
  MintedToken,
  TokenRecord,
  ListTokensInput,
  RevokeTokenInput,
  Project,
  CreateProjectInput,
  ScaffoldInput,
  PlatformApp,
  AppPricingBeneficiary,
  AppPricingResource,
  AppPricingSnapshot,
  ExchangeGitHubCodeInput,
  GitHubIdentity,
  ListUserProjectsInput,
  ListUserDeploymentsInput,
  ListUserProjectDeploymentsInput,
  ListUserProjectTransactionsInput,
  ListUserProjectLogsInput,
  GetUserProjectUsageInput,
  GetBuilderApplicationDetailInput,
  GetBuilderApplicationInput,
  BuilderApplication,
  OwnedOperateProjectInput,
  BotRegistration,
  BotRegistrationApp,
  CreateUserProjectBotInput,
  DeleteUserProjectBotInput,
  CreateUserBotInput,
  UpdateUserBotInput,
  DeleteUserBotInput,
  ProjectSdkUpgradeResult,
  ProjectSdkUpgradeStatusResult,
  OperateTransaction,
  OperateTransactionCursor,
  OperateTransactionsResult,
  OperateUsageDailyRow,
  OperateUsageBreakdownRow,
  OperateUsageResult,
  OperateStatementSummary,
  OperateStatementRevenueRow,
  OperateStatementChargeRow,
  OperateStatementEntry,
  OperateStatementResult,
  OperatePartnerPaymentSummary,
  OperatePartnerPaymentResource,
  OperatePartnerPaymentBucket,
  OperatePartnerPaymentEvent,
  OperatePartnerPayments,
  OperateModelKeyAttribution,
  OperateLogEntry,
  OperateLogCursor,
  OperateLogsResult,
  UserOperateBatchInput,
  GetUserObservabilityInput,
  GetUserPaymentsInput,
  GetUserStatementsInput,
  ListUserTransactionsInput,
  ListUserLogsInput,
  UserProjectRef,
  UserTransactionRow,
  UserTransactionsResult,
  UserLogRow,
  UserLogsResult,
  OperateAppHealth,
  OperateAppDetailTool,
  OperateAppDetailResult,
  OperateDashboardLink,
  OperateObservabilityResult,
  OperateObservabilitySnapshot,
  OperatePaymentProjectResult,
  DeploymentRecord,
  DeactivateApplicationInput,
  ListDeploymentRecordsInput,
  ListDeploymentRecordsResult,
  IngestSecretsInput,
  IngestSecretsResult,
  ListAppSecretsInput,
  RemoveAppSecretInput,
  ListSecretsInput,
  ListSecretsResult,
  UserProject,
  UserProjectAppsResult,
  UserDeployment,
  UserDeploymentsCursor,
  UserDeploymentsPage,
  UserProjectDeploymentApp,
  UserProjectLatestDeployment,
  GetUserProjectRequiredSecretsInput,
  UserProjectRequiredSecretsResult,
  RedactedDeploymentSecret,
  RedactedDeploymentEnvVar,
  PromoteInput,
  PromoteResult,
} from "./types";

export type {
  ActivationRequestInput,
  ActivationRequestPayload,
  DiscordWebhookBody,
} from "./activation-request";

export type {
  SecretSlot,
  ReleaseManifest,
  ReleaseManifestPlugin,
} from "./types";
