import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";

import { normalizeGithubRepo, sha256Prefixed, stageFiles } from "../src/deployment-json";

// NOTE: manifest generation (`buildDeploymentManifest`/`validateManifest`) moved
// server-side (the backend builds + commits `.aomi/deployment.json` — Phase 6),
// so those suites were removed. The client still stages + hashes files.

describe("normalizeGithubRepo", () => {
  it("strips scheme/suffix and lowercases", () => {
    const want = "aomi-labs/krexa-hosted-apps";
    expect(normalizeGithubRepo("https://github.com/aomi-labs/krexa-hosted-apps.git")).toBe(want);
    expect(normalizeGithubRepo("git@github.com:Aomi-Labs/Krexa-Hosted-Apps")).toBe(want);
    expect(normalizeGithubRepo("aomi-labs/krexa-hosted-apps/")).toBe(want);
  });
});

describe("sha256Prefixed", () => {
  it("matches CI's sha256:<hex> form", () => {
    const hex = createHash("sha256").update("hello").digest("hex");
    expect(sha256Prefixed("hello")).toBe(`sha256:${hex}`);
  });
});

describe("stageFiles", () => {
  it("computes sha256+bytes and sorts by path", () => {
    const staged = stageFiles("app", { "z.txt": "z", "a.txt": "aa" });
    expect(staged.map((f) => f.path)).toEqual(["a.txt", "z.txt"]);
    expect(staged[0]).toEqual({
      path: "a.txt",
      sha256: sha256Prefixed("aa"),
      bytes: 2,
    });
  });

  it("normalizes backslashes and ./ prefixes", () => {
    const staged = stageFiles("app", { "./sub\\b.txt": "x" });
    expect(staged[0].path).toBe("sub/b.txt");
  });

  it("rejects empty bundles", () => {
    expect(() => stageFiles("app", {})).toThrowError(/no files to deploy/);
  });

  it("rejects absolute paths", () => {
    expect(() => stageFiles("app", { "/etc/passwd": "x" })).toThrowError(/must be relative/);
  });

  it("rejects '..' traversal", () => {
    expect(() => stageFiles("app", { "../other/app.ts": "x" })).toThrowError(/may not contain/);
  });

  it("rejects the reserved manifest path", () => {
    expect(() => stageFiles("app", { ".aomi/deployment.json": "{}" })).toThrowError(
      /generated by the deploy client/,
    );
  });

  it("rejects duplicate paths after normalization", () => {
    expect(() => stageFiles("app", { "a.txt": "1", "./a.txt": "2" })).toThrowError(/duplicate/);
  });
});
