import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";

import {
  buildDeploymentManifest,
  normalizeGithubRepo,
  sha256Prefixed,
  stageFiles,
  validateManifest,
} from "../src/deployment-json";
import type { PlatformDescriptor } from "../src/contract";

const KREXA: PlatformDescriptor = {
  name: "krexa",
  source_repo: "aomi-labs/krexa-hosted-apps",
  publish_branch: "publish",
  app_path_prefix: "apps",
  release_tag_convention: "apps-{app_slug}-{short_commit}",
  visibility: "private",
};

describe("normalizeGithubRepo", () => {
  it("strips scheme/suffix and lowercases", () => {
    const want = "aomi-labs/krexa-hosted-apps";
    expect(normalizeGithubRepo("https://github.com/aomi-labs/krexa-hosted-apps.git")).toBe(want);
    expect(normalizeGithubRepo("git@github.com:Aomi-Labs/Krexa-Hosted-Apps")).toBe(want);
    expect(normalizeGithubRepo("aomi-labs/krexa-hosted-apps/")).toBe(want);
  });
});

describe("sha256Prefixed", () => {
  it("matches CI's sha256:<hex> form", () => {
    const hex = createHash("sha256").update("hello").digest("hex");
    expect(sha256Prefixed("hello")).toBe(`sha256:${hex}`);
  });
});

describe("stageFiles", () => {
  it("computes sha256+bytes and sorts by path", () => {
    const staged = stageFiles("app", { "z.txt": "z", "a.txt": "aa" });
    expect(staged.map((f) => f.path)).toEqual(["a.txt", "z.txt"]);
    expect(staged[0]).toEqual({
      path: "a.txt",
      sha256: sha256Prefixed("aa"),
      bytes: 2,
    });
  });

  it("normalizes backslashes and ./ prefixes", () => {
    const staged = stageFiles("app", { "./sub\\b.txt": "x" });
    expect(staged[0].path).toBe("sub/b.txt");
  });

  it("rejects empty bundles", () => {
    expect(() => stageFiles("app", {})).toThrowError(/no files to deploy/);
  });

  it("rejects absolute paths", () => {
    expect(() => stageFiles("app", { "/etc/passwd": "x" })).toThrowError(/must be relative/);
  });

  it("rejects '..' traversal", () => {
    expect(() => stageFiles("app", { "../other/app.ts": "x" })).toThrowError(/may not contain/);
  });

  it("rejects the reserved manifest path", () => {
    expect(() => stageFiles("app", { ".aomi/deployment.json": "{}" })).toThrowError(
      /generated by the deploy client/,
    );
  });

  it("rejects duplicate paths after normalization", () => {
    expect(() => stageFiles("app", { "a.txt": "1", "./a.txt": "2" })).toThrowError(/duplicate/);
  });
});

describe("buildDeploymentManifest", () => {
  const commit = "0123456789abcdef0123456789abcdef01234567";

  it("produces a contract-valid manifest", () => {
    const staged = stageFiles("krexa-finance", { "index.html": "<html>", "aomi.toml": "x" });
    const manifest = buildDeploymentManifest({
      slug: "krexa-finance",
      displayName: "Krexa Finance",
      descriptor: KREXA,
      staged,
      sourceCommit: commit,
      serverTags: ["staging"],
      isPublic: false,
      now: 1_700_000_000,
    });

    expect(manifest.app).toMatchObject({
      name: "krexa-finance",
      display_name: "Krexa Finance",
      platform: "krexa",
      git: "https://github.com/aomi-labs/krexa-hosted-apps",
      public: false,
      server_tags: ["staging"],
    });
    expect(manifest.platform).toMatchObject({
      name: "krexa",
      github_repo: "aomi-labs/krexa-hosted-apps",
    });
    expect(manifest.target).toMatchObject({
      branch: "publish",
      app_path: "apps/krexa-finance",
      release_tag: "apps-krexa-finance-0123456789ab",
      server_tags: ["staging"],
    });
    expect(manifest.source.commit).toBe(commit);
    expect(manifest.state).toEqual({ pushed: true, deployed: true, activated: false });
    expect(manifest.files.length).toBe(2);
    expect(manifest.updated_at).toBe(1_700_000_000);

    // The generated manifest must pass the CI validator rules.
    expect(() => validateManifest(manifest, KREXA)).not.toThrow();
  });

  it("defaults display_name to slug", () => {
    const staged = stageFiles("app", { "a.txt": "x" });
    const m = buildDeploymentManifest({
      slug: "app",
      descriptor: KREXA,
      staged,
      sourceCommit: commit,
      serverTags: ["staging"],
      isPublic: false,
    });
    expect(m.app.display_name).toBe("app");
  });
});

describe("validateManifest", () => {
  const commit = "abcabcabcabcabcabcabcabcabcabcabcabcabca";
  const staged = stageFiles("app", { "a.txt": "x" });
  const good = buildDeploymentManifest({
    slug: "app",
    descriptor: KREXA,
    staged,
    sourceCommit: commit,
    serverTags: ["staging"],
    isPublic: false,
  });

  it("rejects a wrong platform name", () => {
    expect(() => validateManifest({ ...good, platform: { ...good.platform, name: "community" } }, KREXA)).toThrow();
  });

  it("rejects a tampered release tag", () => {
    expect(() =>
      validateManifest({ ...good, target: { ...good.target, release_tag: "apps-app-deadbeefdead" } }, KREXA),
    ).toThrow();
  });

  it("rejects an empty files array", () => {
    expect(() => validateManifest({ ...good, files: [] }, KREXA)).toThrow();
  });
});
