import type { FC, SVGProps } from "react";
import {
  AcrossIcon,
  AllAppsIcon,
  BinanceIcon,
  BybitIcon,
  CowIcon,
  DefillamaIcon,
  DuneIcon,
  DydxIcon,
  GmxIcon,
  HyperliquidIcon,
  KaitoIcon,
  KalshiIcon,
  KhalaniIcon,
  LifiIcon,
  LimitlessIcon,
  ManifoldIcon,
  MorphoIcon,
  NeynarIcon,
  OkxIcon,
  OneInchIcon,
  ParaIcon,
  PelagosIcon,
  PolymarketIcon,
  XIcon,
  YearnIcon,
  ZeroxIcon,
  ZoraIcon,
} from "./apps";

const APP_ICONS: Record<string, FC<SVGProps<SVGSVGElement>>> = {
  default: AllAppsIcon,
  across: AcrossIcon,
  binance: BinanceIcon,
  bybit: BybitIcon,
  cow: CowIcon,
  defillama: DefillamaIcon,
  dune: DuneIcon,
  dydx: DydxIcon,
  gmx: GmxIcon,
  hyperliquid: HyperliquidIcon,
  kaito: KaitoIcon,
  kalshi: KalshiIcon,
  khalani: KhalaniIcon,
  lifi: LifiIcon,
  limitless: LimitlessIcon,
  manifold: ManifoldIcon,
  morpho: MorphoIcon,
  neynar: NeynarIcon,
  okx: OkxIcon,
  oneinch: OneInchIcon,
  para: ParaIcon,
  pelagos: PelagosIcon,
  polymarket: PolymarketIcon,
  "polymarket-rewards": PolymarketIcon,
  x: XIcon,
  yearn: YearnIcon,
  zerox: ZeroxIcon,
  zora: ZoraIcon,
  "0x": ZeroxIcon,
  "1inch": OneInchIcon,
  "li-fi": LifiIcon,
  "li.fi": LifiIcon,
  getpara: ParaIcon,
  "para-customer": ParaIcon,
  "para-consumer": ParaIcon,
  para_consumer: ParaIcon,
  twitter: XIcon,
};

export function getAppIcon(
  appId: string,
): FC<SVGProps<SVGSVGElement>> | undefined {
  return APP_ICONS[appId];
}
